### ISSUE TITLE
VoodooInput.kext exists redundant/ twice | Questions about your repo

### ISSUE THREAD

**Issue by LeeBinder** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.5-Hackintosh#6]
Hi whatnameisit, I hope you're in good mood and health.

I'm peeking over into your fine repo here every once in a while :) 

Hint: the VoodooI2C dev team agreed to include VoodooInput as a plugin right into VoodooI2C.kext:

https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.3-Hackintosh/tree/master/Clover%20EFI/EFI/CLOVER/kexts/Other/VoodooI2C.kext/Contents/PlugIns

So now your separate and thus duplicate VoodooInput kext

https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.3-Hackintosh/tree/master/Clover%20EFI/EFI/CLOVER/kexts/Other/VoodooInput.kext

should be removed and any mod should occur right in the one in VoodooI2C.kext/Contents/PlugIns in alignment with the dev team's specs.

A few questions about your repo, if I may: 

1. Can you elaborate on "Finger ID-implemented VoodooInput and VoodooI2C for persistent gesture input"? What exacgtly does it mean in terms of usage functionality, and which change(s) did you apply in VoodooI2C 2.4 and VoodooInput 1.0.4?

2. why did you move USBPorts.kext to additional?

3. Which problem(s) did you encounter before you switched from config.plist AppleRTC kernel fix to adding RTCMemoryFixup.kext, and did RTCMemoryFixup fix whichever issue(s) for good?

4. I see you're still having "MSR 0xE2 _xcpm_idle instant reboot(c) Pike R. Alpha (Delete this patch after unlocking MSR 0xE2)" active. Doesn't recent Clover unlock MSR 0xE2 by default?

5. What is SSDT-USBX.aml doing? The .dsl code did not tell me much.

6. I see you have not removed pci8086,9d60 in VoodooI2C.kext/Contents/Info.plist. With VoodooI2C < 2.4 I did encounter random kernel panics with that entry present. I would say it can't hurt to remove any entry in there apart from our pci8086,9d61, can't it?

Take your time, I'm not in a hurry.

**Comment by whatnameisit** [comment]
Hey, I'm doing all right, thanks for asking :)
I will have to remove one VoodooInput. Thank you for pointing that out.
1. The finger-id implementation is what's been done in 2.4 release. I just wanted to keep track of when and how the trackpad improved. It doesn't really mean anything to end users.
2. I had made my mind to put USBPorts.kext in *additional* since a long time ago because making one's own kext is recommended in case USB map is different for other laptop models. I copy-and-pasted the kexts and USBPorts too was put into *Other* which is why I made a commit to move it.
3. I have not debugged anything, but Clover's AppleRTC fix is said to break something, whereas this kext has little chance of breaking: https://www.insanelymac.com/forum/topic/321371-lilu-—-kext-and-process-patcher/?page=13&tab=comments#comment-2661420
4. This patch can be deleted after unlocking CFG which allows writes to MSR 0xE2 with no KP and enables extensive CPU power management. The kernel patch was meant to be used in case writes to MSR 0xE2 result in KP, hence disabling writes to that region. I don't know a lot, but CFG unlock has advantage over applying MSR related patches: MSR 0xE2 is not the only MSR patch hackintoshers apply in case CFG cannot be unlocked.
5. The SSDT injects power properties to USB like charging iPhone, iPad, and other devices. In some cases they are needed for data transfer if the current is low. When we all used MBP11,1 as the profile, the power properties were implemented in Apple's AppleBusPowerController.kext and the kexts that depend on it, but newer profiles do not have them in Apple's kexts, but in ACPI device called USBX. There are many ways to apply these properties, like USBPorts.kext, USBX device, or XHC device. I chose USBX because that's what Apple does with real MBP15,4.
6. These days I use a notebook stand and so I use a mouse instead of the trackpad. Every time there is an update on OpenCore or VoodooI2C or VoodooInput update I test once or twice if the trackpad works OK. I have not experienced trackpad failures in a month, but I do remember after the "Random stop" issue was closed I reproduced the random stop once. I don't really know how to reproduce it, so I didn't reopen the issue...
I will remove the duplicate VoodooInput, thanks for that, and I hope this helps!

**Comment by LeeBinder** [comment]
Thanks a lot, whatnameist, very much appreciated! Brief Easter vacation - can reply in a day or so.

**Comment by whatnameisit** [comment]
I deleted RTCMemoryFixup or AppleRTC fix in Clover kernel patch not needed on X510UA-BQ490. tested just now. I got hints from hieplpvip's opencore branch of his Asus-Zenbook-hackintosh.

**Comment by LeeBinder** [comment]
Gotcha, @whatnameisit, thanks for checking back into this ! I'm finally back and should be able to respond tomorrow.
